app = "barbara-agent"
primary_region = "lax"

[build]
  dockerfile = "./Dockerfile"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
  [http_service.concurrency]
    type = "requests"
    soft_limit = 40
    hard_limit = 50

[checks]
  [checks.http]
    type = "http"
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "GET"
    path = "/healthz"
    port = 8080

[vm]
  cpu_kind = "shared"
  cpus = 2
  memory = "1gb"
# or
# [[vm]]
#   size = "shared-cpu-2x"


