app = "equity-livekit-core"
primary_region = "lax"

[build]
  dockerfile = "Dockerfile"

[env]
  REDIS_URL = "redis://equity-redis-server.internal:6379"

[http_service]
  internal_port = 7880
  force_https = true
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
  processes = ["app"]

[[services]]
  protocol = "tcp"
  internal_port = 7880
  processes = ["app"]
  [[services.ports]]
    port = 7880

[[services]]
  protocol = "udp"
  internal_port = 50000
  processes = ["app"]
  [[services.ports]]
    start_port = 50000
    end_port = 60000

