app = "equity-livekit-core"
primary_region = "lax"

[build]
  dockerfile = "Dockerfile"

[env]
  REDIS_URL = "redis://equity-redis-server.internal:6379"

[[services]]
  protocol = "tcp"
  internal_port = 7880
  processes = ["app"]
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
  [[services.ports]]
    port = 80
    handlers = ["http"]
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[[services]]
  protocol = "udp"
  internal_port = 50000
  processes = ["app"]
  [[services.ports]]
    port = 50000
    end_port = 60000

