app = "equity-minio"
primary_region = "lax"

[build]
  image = "minio/minio:latest"

[processes]
  app = "server /data --console-address :9001"

[env]
  MINIO_ROOT_USER = "minioadmin"
  MINIO_ROOT_PASSWORD = "minioadmin"

[[services]]
  internal_port = 9000
  protocol = "tcp"
  processes = ["app"]
  [[services.ports]]
    port = 9000
    handlers = ["tls"]

[[services]]
  internal_port = 9001
  protocol = "tcp"
  processes = ["app"]
  [[services.ports]]
    port = 9001
    handlers = ["tls"]

